### ISSUE TITLE
Get the encryptation key?

### ISSUE THREAD

**Issue by gweberk** [google/edash-packager#100]
Hello,

I'm using the utility to encrypt the media and generate the mpd. I'd like to add others DRMs, I read that I need the KID, and KEY, register them in the DRM licence server's and add the headers in the MPD.

How can I get the KEY after encrypt with packager? If I use fixed keys how can I register them in Google licence server?

**Comment by kqyang** [comment]
The KEY is not exposed or stored right now. You could update https://github.com/google/edash-packager/blob/master/packager/media/base/widevine_key_source.cc to save the key or register the key with other DRM license servers there.

You may also use fixed keys and register the keys in Google license server. @imalex can you advise @gweberk how to do it? Thanks.

**Comment by imalex** [comment]
For access to the Google Widevine license server, you'll need to complete a license agreement first and then receive credentials for license server access.

http://www.widevine.com/contact.html

**Comment by kqyang** [comment]
I am closing this bug. @gweberk Feel free to re-open it if you have more questions.

**Comment by gweberk** [comment]
Thank you!
