### ISSUE TITLE
[Packager] Removing the oldest segments  

### ISSUE THREAD

**Issue by Tomtom777** [google/edash-packager#101]
Hello,

I want to test a several-hours dash streaming using Packager app

Please, is there a specific command line option to make "./Debug/packager" app removing segments older than X minutes from HDD and their link into the mpd manifest?

More generally, is there a complete documentation about Packager's command line options?

Thanks

**Comment by kqyang** [comment]
We don't support removing oldest segments in packager right now - we are still evaluating whether it should be supported in packager internally. You may use a cron job to remove old segments periodically.

Running the packager directly shows the list of command line options.

**Comment by Tomtom777** [comment]
Thank you very much!

**Comment by peyoh** [comment]
No, 
you can set timeshiftBufferDepth and remove only raw data files beyond it.

**Comment by kqyang** [comment]
Correct, only segments within --time_shift_buffer_depth (the default value is 1800 seconds right now, i.e. 30 minutes) is included in the mpd.

**Comment by Tomtom777** [comment]
thanks!
