### ISSUE TITLE
WebVTT Support in MPD

### ISSUE THREAD

**Issue by techwizblog** [google/edash-packager#12]
We require to support subtitle Webvtt. Is there way we can use edash-packager to include subtitle webvtt as part of dash generation process.

**Comment by tinskip** [comment]
Hi.

Currently your only option is to edit the mpd to add the subtitle file
representations. We do have plans to support WebVTT and TTML subtitles in
our packaging going forward. Check periodically.


On Sun, Mar 22, 2015 at 3:05 PM, techwizblog <notifications@github.com>
wrote:

> We require to support subtitle Webvtt. Is there way we can use
> edash-packager to include subtitle webvtt as part of dash generation
> process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/edash-packager/issues/12>.
>



-- 
Thomás Inskip | Software Engineer | tinskip@google.com | +1 650 241 9697

**Comment by kqyang** [comment]
It is now supported.
