### ISSUE TITLE
HEVC(H.265) Support

### ISSUE THREAD

**Issue by nibaboojit** [google/edash-packager#13]
are edash-packager is HEVC(H.265) codec support plan? 
If you have a support plan to show up?

**Comment by kqyang** [comment]
Yes, that will be likely supported next quarter. I have just created a [public mailing list](https://groups.google.com/forum/#!forum/edash-users) for announcements.You may subscribe to it to receive the updates.

**Comment by nibaboojit** [comment]
thanks for public mailing list :)
but are you saying next quarter means 2nd quarter?

**Comment by kqyang** [comment]
Yes.

**Comment by nibaboojit** [comment]
thank you :)
