### ISSUE TITLE
Python DASH Player

### ISSUE THREAD

**Issue by Avbrella** [google/edash-packager#16]
Could this project be used to implement a encryption-agnostic DASH player in Python?

**Comment by tinskip** [comment]
Could you please elaborate a little bit?  What do you mean by
"encryption-agnostic"?  And do you mean could you interface with the APIs
via SWIG?  Or do you mean if it could be used to package content for said
player?


On Thu, Apr 30, 2015 at 1:10 AM, Avbrella <notifications@github.com> wrote:

> Could this project be used to implement a encryption-agnostic DASH player
> in Python?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/edash-packager/issues/16>.
>



-- 
Thomás Inskip | Software Engineer | tinskip@google.com | +1 650 241 9697

**Comment by Avbrella** [comment]
I'm wondering if this code could be used to implement "pre-demuxing" of DASH XML manifests so a media player software called Kodi can begin implementing DASH streams. I know a lot of addons and plugins in the Kodi ecosystem are written in Python which is where the language specification comes from. Most DASH implementations (with a plugin/library construction) I'm finding are written in Flash or Javascript due to the overwhelming market share web browsers have as far as demand for DASH playback is concerned.

**Comment by tinskip** [comment]
This package can be used to decrypt the media streams if you have access to
the keys.  For parsing the (XML manifest) MPD file, probably the best thing
to do is use python directly.


On Thu, Apr 30, 2015 at 12:11 PM, Avbrella <notifications@github.com> wrote:

> I'm wondering if this code could be used to implement "pre-demuxing" of
> DASH XML manifests so a media player software called Kodi can begin
> implementing DASH streams. I know a lot of addons and plugins in the Kodi
> ecosystem are written in Python which is where the language specification
> comes from. Most DASH implementations (with a plugin/library construction)
> I'm finding are written in Flash or Javascript due to the overwhelming
> market share web browsers have as far as demand for DASH playback is
> concerned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/edash-packager/issues/16#issuecomment-97860631>
> .
>



-- 
Thomás Inskip | Software Engineer | tinskip@google.com | +1 650 241 9697

**Comment by tinskip** [comment]
Closing issue.
