### ISSUE TITLE
MPEG-TS (mp2v,mp2a) Parser Failure

### ISSUE THREAD

**Issue by nrmmota** [google/edash-packager#17]
[0611/145139:ERROR:packager_main.cc(136)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file udp://239.192.1.102:1234

I'm using an Al Jazeera channel coming from Astra 19.

Not sure if this problem is invalid due to the fact that I'm trying to use mpeg legacy codecs. mp2v and mp2.

ffmpeg -i udp://239.192.1.102:1234
...
[mpegts @ 0x9a6a7e0] Unable to seek back to the start
[mpeg2video @ 0x9a89160] 0x0 is invalid
    Last message repeated 4 times
[mpegts @ 0x9a6a7e0] max_analyze_duration 5000000 reached at 5000000 microseconds
[mpegts @ 0x9a6a7e0] Estimating duration from bitrate, this may be inaccurate
Input #0, mpegts, from 'udp://239.192.1.102:1234':
  Duration: N/A, start: 72.482444, bitrate: 128 kb/s
  Program 7009
    Metadata:
      service_name    : Al Jazeera Channel
      service_provider: GLOBECAST
    Stream #0:0[0x2c5]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p, 544x576 [SAR 32:17 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x2d9](ara): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 128 kb/s

**Comment by kqyang** [comment]
Unfortunately, mp2v and mp2a are not supported.
