### ISSUE TITLE
How can I receive signingkey - registration process with Google License server

### ISSUE THREAD

**Issue by superbderrick** [google/edash-packager#20]
HI nice to meet you I am Derrick in korea.
I have a simple question , I'd like to make encrypted contents with google Widevine Drm using edash-packager and then,
I hope to play (test) with sharka player and my Android test local player with encrypted content.
After read README document, It seems to need a some registration process with Google License server.
After to convert RSA signing key to .Der, How can I register to google license server my signingkey, ?

Thanks Best Regards
Derrick.

**Comment by kqyang** [comment]
You'll need to sign up with our Google NDA and Widevine Master License Agreements. 

Go to http://www.widevine.com/contact.html and create a general / sales inquiry.

**Comment by superbderrick** [comment]
Ok Thanks you 
-Derrick

**Comment by superbderrick** [comment]
HI kqyang


I have a one question about DASH encrypted contents, 
I am trying to make encrypted dash contents with live profile using normal mp4 file( not from live streaming server).

So, I could made some contents based on READ.ME Document  but It looks like they are not perfect.

I inputed like this 

.././packager input=normal_audio.mp4,stream=audio,output=encrypted_audio.mp4 \
			  input=normal_video.mp4,stream=audio,output=encrypted_video.mp4 \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \
--crypto_period_duration 140

Result of the conversion is mpd file with segment files, however I observed that first segment file is not encrypted properly. and initialization segment file also, 
How Can I encrypt to first segment file and initialization segment file
Best Regard Derrick.

**Comment by kqyang** [comment]
There are 10 seconds clear lead by default. You could set it to 0 by adding ```--clear_lead 0``` to command line.

The initialization segment will never be encrypted per [CENC spec] (https://www.iso.org/obp/ui/#iso:std:iso-iec:23001:-7:ed-1:v1).

**Comment by superbderrick** [comment]
Thanks replay quickly, 
I was wrong questions , I know that  the initialization segment will never be encrypted per CENC spec.

So , What I am saying that, initialization segment file doesn't have any information about pssh data for DRM ,

 In spite of I added -- flag ' --clear_lead 0 ' 
Thanks 
Best Regards 
Derrick,

**Comment by kqyang** [comment]
With key rotation, the encryption keys may change from this segment to another segment, i.e. pssh for this segment could be different for different segments, so instead of putting pssh in the initialization segment, we put it in the media segments.

**Comment by superbderrick** [comment]
Thanks you very much. 
Best Regards Derrick.
