### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by kamilghais** [google/edash-packager#3]
Hi,
can someone please compile the windows binaries for us? We did not succeed creating ninja build file, it says the 'zlib/zlib.gyp' is missing.
Help appreciated.
  Kamil Ghais

**Comment by sanbhatt** [comment]
Hi kqyang, is there a timeline to when windows build may be fixed?

**Comment by kqyang** [comment]
No, we don't have a timeline for windows support at this time.

**Comment by kqyang** [comment]
Duplicate of issue #22
