### ISSUE TITLE
More examples about driver program (packager)

### ISSUE THREAD

**Issue by leandromoreira** [google/edash-packager#30]
I wrote a Dockerfile to test dash (streaming and [shaka-player](https://github.com/google/shaka-player)) and I miss more samples about **packager** usage,  I noticed that if you type `packager` with no args, a help will be shown and that's nice :cake: .

The examples I missed:
* **vod** 1 input to 1 mpd (segmented audio/video)
* **vod** 1 input(720p) to 1 mpd (segmented audio/video and by bitrates) (1)
* **live** 1 input(rtmp) to 1 mpd (segmented audio/video)
* **live** 1 input(file in loop) to 1 mpd (segmented audio/video) (2)
* **live** 1 input(file in loop) to 1 mpd (segmented audio/video and multiples bitrates) (2)

(1) for the recoding (like splitting one single file into *n* different bitrates) we could use ffmpeg before.
(2) we also can achieve this by using ffmpeg (at least to generate infinite input to `packager`)

I don't know if it's your purpose but maybe make this packager a real `distro package` would be nice.

```Dockerfile
FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

# update, upgrade and install basic packages
RUN apt-get update && apt-get upgrade -y && apt-get clean
RUN apt-get install -y \
            build-essential \
            wget \
            git \
            python \
            subversion

# install depot_tools http://www.chromium.org/developers/how-tos/install-depot-tools
RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
ENV PATH /depot_tools:$PATH

# install edash-packager
RUN mkdir edash_packager
WORKDIR edash_packager
RUN gclient config https://www.github.com/google/edash-packager.git --name=src
RUN gclient sync
RUN cd src && ninja -C out/Release
ENV PATH /edash_packager/src/out/Release:$PATH

# adding your media
ADD your_media.mp4 /
```

**Comment by leandromoreira** [comment]
I was able to at least generate a playable vod mpd and its resource. :)
```bash
# vod - not segmented
packager input=/dkctf.mp4,stream=audio,output=dkctfa.mp4 input=/dkctf.mp4,stream=video,output=dkctfv.mp4 --profile on-demand --mpd_output dkctf.mpd
```

**Comment by kqyang** [comment]
Cool. Yes, there is actually an example for vod 1 input to 1 mpd.

```bash
packager \
  input=sintel.mp4,stream=audio,output=sintel_audio.mp4 \
  input=sintel.mp4,stream=video,output=sintel_video.mp4 \
--profile on-demand \
--mpd_output sintel_vod.mpd
```

As for (1), you'll need to use ffmpeg to transcode the input first.

edash-packager does not support rtmp yet. A rtmp protocol parser implementation similar to https://github.com/google/edash-packager/blob/master/packager/media/file/udp_file_posix.cc needs to be implemented. You are welcomed to contribute to this project if you know how to do it :)

For input (file in loop), are you saying playing the same file in loop? That is not really live. But You can generate a simulated "live" stream from the file using vlc: (I don't know if you can do the same thing with ffmpeg)

```bash
vlc input.mp4 --sout '#transcode{vcodec=h264,scale=Auto}:udp{mux=ts,dst=239.255.0.1:1234}'
```

Then you can package it, e.g.

```bash
packager 'input=udp://239.255.0.1:1234,stream=audio,init_segment=live-audio.mp4,segment_template=live-audio-$Number$.mp4'  \
         'input=udp://239.255.0.1:1234,stream=video,init_segment=live-video.mp4,segment_template=live-video-$Number$.mp4'  \
         --profile live --mpd_output live.mpd
```

**Comment by leandromoreira** [comment]
Thanks @kqyang , to implement rtmp I have to overcome two challenges:

* learn [rtmp](http://www.adobe.com/content/dam/Adobe/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf) better, maybe get some understanding from [nginx-rtmp](https://github.com/arut/nginx-rtmp-module).
* learn and apply c++

Anyway, thanks a lot and I'll try to find time to, at least, try it. ;)

**Comment by kqyang** [comment]
Thanks.

**Comment by kqyang** [comment]
Ooops, I forgot to reply to the other comments you have on distro package. No, that is not on purpose. I didn't create it just because I am not familiar with package distribution under Linux. It will be awesome if you can contribute your script and advise how to use it.

**Comment by leandromoreira** [comment]
@kqyang I'm gonna create a PR with the Dockerfile and some advices on how to use (README)

**Comment by kqyang** [comment]
Cool. Thanks.
