### ISSUE TITLE
When profile is live for packager program then we see an error

### ISSUE THREAD

**Issue by pavanpalli** [google/edash-packager#37]
./packager \
input=/home/pavan/Downloads/content/subtitles.mp4,stream=video,output=encrypted_subtitle.mp4 \ input=/home/pavan/Downloads/content/subtitles.mp4,stream=audio,output=encrypted_audio.mp4 \ --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" --crypto_period_duration 1800 --output_media_info -profile live

Profile live: set --single_segment to false.
[0831/155205:ERROR:packager_main.cc(233)] Not implemented reached in bool edash_packager::media::RunPackager(const StreamDescriptorList&)ERROR: --output_media_info is only supported if --single_segment is true.

**Comment by kqyang** [comment]
--output_media_info is not supported with live. You may output to a mpd directly:

./packager \
input=/home/pavan/Downloads/content/subtitles.mp4,stream=video,output=encrypted_subtitle.mp4 \ input=/home/pavan/Downloads/content/subtitles.mp4,stream=audio,output=encrypted_audio.mp4 \ --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" --crypto_period_duration 1800 --mpd_output encrypted.mpd -profile live

**Comment by abhi0001** [comment]
/media# packager input=/media/example.mp4,stream=audio,output=audio.mp4 \
>          input=/media/example.mp4,stream=video,output=video.mp4 \
>          --profile on-demand --mpd_output example.mpd
[1208/133449:INFO:demuxer.cc(55)] Initialize Demuxer for file '/media/example.mp4'.
[1208/133449:ERROR:demuxer.cc(91)] Not implemented reached in edash_packager::media::Status edash_packager::media::Demuxer::Initialize()
[1208/133449:ERROR:packager_main.cc(250)] Demuxer failed to initialize: 4 (UNIMPLEMENTED): Container not supported.

**Comment by kqyang** [comment]
@abhi0001 Can you open a new issue if you are seeing problems? Also can you describe a little bit more on what the problem is? From the log, looks like you feed in some file format we don't support yet.

**Comment by abhi0001** [comment]
thanks for spending your valuable time in replying me ...can i contact you
directly or have your email address for fixing issues i face with edash
packager because i am trying to do this for more than a month so every time
i do i get stuck with some steps

**Comment by kqyang** [comment]
No problem.

You can always open an issue in
https://github.com/google/edash-packager/issues if you believe it is a bug
in edash-packager.

I am also available in edash mailing list:
https://groups.google.com/forum/#!forum/edash-users. Feel free to ask
questions or start discussions in mailing list and we will make sure every
message is replied.




-- KongQun Yang (KQ)
