### ISSUE TITLE
Unable to play live profile with .js referent players

### ISSUE THREAD

**Issue by peyoh** [google/edash-packager#38]
Hello, 
since several weeks we are trying to find why some android devices (Lenovo K920, Samsung S6 )  with android 5.x are unable to 
play content generated by edash_packager with .JS  reference players as 
http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/
 
On other devices (Nexus 9, PC with Win/Linux and Chrome) video is played around 10-20 sec and after that freezes. We cannot find any error logs generated by edash packager.

The 3 input streams are encoded in h264 main profile (the same story is with Baseline also), muxed in MPEG-TS and streamed over 3 multicast groups. 239.100.2.1,239.101.2.1 and 239.102.2.1. Only the first group contains AAC audio. Video in every group is in different size - 1080,720 and 576. 
The groups are received by the packager like:
packager  --udp_interface_address=172.18.0.10 'input=udp://239.100.2.1:1234,stream=audio,init_segment=/storage/web/dash/bnt1/bnt1_edash-audio.m4a,segment_template=/storage/web/dash/bnt1/bnt1_edash-audio-$Number$.m4a'    'input=udp://239.100.2.1:1234,stream=video,init_segment=/storage/web/dash/bnt1/bnt1_edash-video-1080.m4v,segment_template=/storage/web/dash/bnt1/bnt1_edash-video-1080-$Number$.m4v' 'input=udp://239.101.2.1:1234,stream=video,init_segment=/storage/web/dash/bnt1/bnt1_edash-video-720.m4v,segment_template=/storage/web/dash/bnt1/bnt1_edash-video-720-$Number$.m4v' 'input=udp://239.102.2.1:1234,stream=video,init_segment=/storage/web/dash/bnt1/bnt1_edash-video-576.m4v,segment_template=/storage/web/dash/bnt1/bnt1_edash-video-576-$Number$.m4v' --profile live --mpd_output /storage/web/dash/bnt1/bnt1.mpd -time_shift_buffer_depth 1800

Because I was unable to fix the issue and find something wrong in the code, on the transcoder I catch the streams and generate MP4 file. This file I passed to another packetizer (another project)  and create .segments and .mpd file with it. I do this to exclude issues with the source streams. With the files created from the new packetizer I'am able to play the video without issues with the same profile (live) and segment templates, count based. 

How I could help to find if this is a issue with packager SDK?

BRS/
Peyo

**Comment by kqyang** [comment]
Thanks for reporting the issue. A couple of questions:

1. Are you using latest edash-packager on github?

2. Can you attach a mpd? We can take a look to see if everything is already.

3. When the video freezes, do you see any error messages on javascript debug console?

Also, can you try if the generated outputs works with shaka player: https://shaka-player-demo.appspot.com? (which is also open source @ https://github.com/google/shaka-player)

**Comment by peyoh** [comment]
Hello,
1) I'm using the latest packager from github.
2) Here is the link:
https://drive.google.com/file/d/0Bx_EoTGLxRt3Zks3VC16ZDU4Y2c/view?usp=sharing
3) No messages. 

We try with shaka also. but with the same result. 

BRS/
Peyo

**Comment by kqyang** [comment]
Thanks. Can you upload some media files as well, e.g. all the init segments and media segments from 0 to 10?

**Comment by peyoh** [comment]
Here is the media link:
It's around 250 MB btw, 3 video and 1 audio streams with 10 files per stream.
https://drive.google.com/file/d/0Bx_EoTGLxRt3Y3JhUGJmS0s4Q0E/view?usp=sharing

**Comment by peyoh** [comment]
I just update shaka player to the commit from 9'th Sep, 
and it works now, BTW. 
Except every time on the console I see:
[0911/114341:WARNING:mpd_builder.cc(756)] Found a gap of size 4320 > kRoundingErrorGrace (5). The new segment starts at 369673920 but the previous segment ends at 369669600
Shaka player "freezes" and starts to retry the last 3 audio files unlimited reads from the web server.
But I thing this is a player issue. Not edash SDK issue. 
What cause this error? I mean, stream issue, right?

BRS/
Peyo

**Comment by kqyang** [comment]
Another possibility is that packager was not able to process fast enough, results in some frame loss. Does it work well if you change to package only one stream?

**Comment by peyoh** [comment]
Hello. 
Sorry for my late reply.
We've already discuss the issue with shaka developers. 

https://github.com/google/shaka-player/issues/180

Thank you,
Peyo
