### ISSUE TITLE
Blank output from Widevine Classic adaptive packages as source

### ISSUE THREAD

**Issue by P120D1GY** [google/edash-packager#42]
Running edash packager with enable_widevine_decryption on a Widevine Classic Adaptive package causes outputted file to have large blanks. The packager extracts the video stream successfully but leaves large chunks of empty video after the video stream with actual content ends. Is there a way to end the output when the actual video content ends when using an adaptive package as the source?

E.g.
`packager input=adaptive_widevine_classic_adaptive.wvm,stream=0,output=output.mp4 --enable_widevine_decryption --signer "[PORTAL]" --key_server_url "https://license.widevine.com/cenc/getcontentkey/[PORTAL]" --aes_signing_key "[KEY]" --aes_signing_iv "[IV]"`

**Comment by kqyang** [comment]
We will look into it. Do you have any sample content with this behavior?

**Comment by tinskip** [comment]
Neither the Widevine Classic packager nor the eDASH Packager add empty video or audio frames to the content.  The empty video must be present in the original content which was fed into the WVM packager.  Can you check the contents of the ISO-BMFF output by eDASH Packager to see if the video duration matches what you are seeing?

**Comment by P120D1GY** [comment]
Apologies, false alarm. Media info shows correct duration, Ubuntu + VLC also pickup correct length, it's Mac OS X Quicktime that doesn't seem to correctly support the decoded output, thus displaying an incorrect total duration.
