### ISSUE TITLE
Support HEVC

### ISSUE THREAD

**Issue by kqyang** [google/edash-packager#46]

**Comment by hexiay** [comment]
Really looking forward to hevc

**Comment by Tomtom777** [comment]
Is HEVC over TS stream supported?

Thanks!

**Comment by TheModMaker** [comment]
Not yet, but we are working on it and we will have support soon.  Currently, we only support HEVC in MP4 (both clear and encrypted).

**Comment by Tomtom777** [comment]
Thank you very much!
Do you have a more precise idea about the date when edash will support it ?

I really looking forward to it!

**Comment by kqyang** [comment]
It will be some time in May.

**Comment by hexiay** [comment]
Beyond the topic, which player are you guys using to play HEVC content? We
only get VLC can do this.
We are also looking for a browser if it can support HEVC...


Thanks,
Wanxiang

**Comment by kqyang** [comment]
You should be able to find players with HEVC support in Android.

Also, you may try to build customized version of Chromium with HEVC support: https://code.google.com/p/chromium/codesearch#chromium/src/media/BUILD.gn&l=20

**Comment by hexiay** [comment]
Thanks Kongqun!
