### ISSUE TITLE
Support access units without AUD

### ISSUE THREAD

**Issue by peyoh** [google/edash-packager#47]
Hello,
I'm unable to run demuxer on this file:
packager input=gstreamer.ts,stream=video,output=output.mp4
[1029/115327:INFO:demuxer.cc(54)] Initialize Demuxer for file 'gstreamer.ts'.
[1029/115327:ERROR:packager_main.cc(156)] Demuxer failed to initialize: 6 (END_OF_STREAM):

ffmpeg recognizes this file as:
Input #0, mpegts, from 'gstreamer.ts':
  Duration: 00:00:13.78, start: 3600.000000, bitrate: 2014 kb/s
  Program 1 
    Stream #0:0[0x41]: Video: h264 (Main) (HDMV / 0x564D4448), yuv420p, 720x576, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1[0x42]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 70 kb/s

File is reachable here:
https://drive.google.com/file/d/0Bx_EoTGLxRt3WkdBMGZtaFpOOXM/view?usp=sharing

It's created with gstreamer.
Can you take a look? Because I'm unable to use any MPEG-TS stream also generated by gstreamer.

BRS/
Peyo

**Comment by kqyang** [comment]
It looks like the stream does not have AUDs (Access Unit Delimiter), which we expect to see in every Access Unit.

We'll take a closer to see if it is legal (spec compliant) to do that.

@tinskip, any thoughts?

**Comment by tinskip** [comment]
IIRC the leading AUD requirement depends on whether the video bitstream is
a Unit Stream (ISO-BMFF mostly), or Byte Stream (or Annex B, MPEG-2
containers).  I am pretty certain it is required for the latter.  But we
can probably relax that restriction.


On Thu, Oct 29, 2015 at 1:30 PM, Kongqun Yang <notifications@github.com>
wrote:

> It looks like the stream does not have AUDs (Access Unit Delimiter), which
> we expect to see in every Access Unit.
>
> We'll take a closer to see if it is legal (spec compliant) to do that.
>
> @tinskip <https://github.com/tinskip>, any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/edash-packager/issues/47#issuecomment-152309368>
> .
>



-- 
Thomás Inskip | Software Engineer | tinskip@google.com | +1 650 241 9697

**Comment by kqyang** [comment]
"ITU-T H-264:2014 7.4.1.2.3 Order of NAL units and coded pictures and association to access units" defines how access units can be extracted, which allows access unit delimiter NAL unit to be omitted from access unit. @TheModMaker is working on a fix.

**Comment by TheModMaker** [comment]
Now it will be able to determine access units without an AUD.  However, the file you provided still will not work because it has timestamp errors.  Several frames have a DTS the same as a previous one.  If you pass it into ffmpeg, it will give warnings about invalid timestamps, and it will make a guess.

**Comment by peyoh** [comment]
Hi TMM,
I'm unable to test it because I no longer use gstreamer. If you are sure, that this enhancement is done, please close the case. 
Cheers!
