### ISSUE TITLE
Invalid MPD manifest

### ISSUE THREAD

**Issue by lpluto** [google/edash-packager#49]
Hi,
Sometimes we receive invalid output MPD manifest when we use "--mpd_output" option. We guess that it may be related to wrong threads synchronization when edash packager writes to output MPD file.

It doesn't happen when we use mpd_generator command.

Sample invalid manifest: [manifest.mpd.txt](https://github.com/google/edash-packager/files/35296/manifest.mpd.txt)

Kind regards,
Lukasz Pluto

**Comment by kqyang** [comment]
No, the thread synchronization issue in #45 should not lead to corrupted mpd output. I don't see how it could happen. @rkuroiwa what do you think?

Lukasz, do you have sample files and a duplicate procedure we can use to duplicate the problem?

**Comment by kqyang** [comment]
No, the

**Comment by kqyang** [comment]
Oops, click the

**Comment by rkuroiwa** [comment]
I think the problem is a race condition in MpdNotifier::Flush() implementations. There are no locks used in Flush() so multiple threads are writing to the same file.
There will be a patch soon that locks the Flush() implementations.

That said, it would be nice to know the repro steps :)

**Comment by kqyang** [comment]
This bug should be fixed with Rintaro's latest cl.

@lpluto Can you try and verify? Let us know the results. Thanks again for reporting the issue!

**Comment by kqyang** [comment]
Close as fixed. @lpluto please reopen it if you are still seeing the problem with latest cl or v1.2.1.

**Comment by lpluto** [comment]
We've updated eDash {ackager on one of our environments and it works now.

Thanks for help!

**Comment by kqyang** [comment]
Great to hear that! Thanks for the update!
