### ISSUE TITLE
DEMUXUR FAILED TO INITIALLIZE.... container failed

### ISSUE THREAD

**Issue by abhi0001** [google/edash-packager#53]
thanks for your reply ...MR.Kongqun Yang i am trying to do with the steps mentioned in https://github.com/google/edash-packager in Using docker for testing / development section and it is providing the following error..

root@b966d054799c:/edash_packager# cd /media
root@b966d054799c:/media# packager input=/media/example.mp4,stream=audio,output=audio.mp4 \
>          input=/media/example.mp4,stream=video,output=video.mp4 \
>          --profile on-demand --mpd_output example.mpd
[1209/034957:INFO:demuxer.cc(55)] Initialize Demuxer for file '/media/example.mp4'.
[1209/034958:ERROR:demuxer.cc(91)] Not implemented reached in edash_packager::media::Status edash_packager::media::Demuxer::Initialize()
[1209/034958:ERROR:packager_main.cc(250)] Demuxer failed to initialize: 4 (UNIMPLEMENTED): Container not supported.
...
it is said that you should be within the container for executing 3steps these are executed within container still and it is having a mp4 video i named it as example.mp4 ..need help to fix this

**Comment by kqyang** [comment]
It means the input is not using a supported format. Can you attach your example.mp4 file?

**Comment by abhi0001** [comment]
i am not able to attach the mp4 file the mail is bouncing back everytime i am trying to do it

**Comment by abhi0001** [comment]
i downloaded it from youtube ...or any normal mp4 files i am trying to move on with i am still stuck with the above error

**Comment by kqyang** [comment]
Can you host it somewhere, e.g. upload to google drive and copy the link here?

**Comment by abhi0001** [comment]
http://en.savefrom.net/#url=http://youtube.com/watch?v=OgJeq4Cwvs4&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=ssyoutube.com 
this is the link i downloaded the mp4 from and was trying to deal with

**Comment by kqyang** [comment]
I am not seeing any problem.

Can you run the below two commands and let me know what happens:

```
packager input=/media/example.mp4 --dump_stream_info
packager input=/edash_packager/src/packager/media/test/data/bear-640x360.mp4 --dump_stream_info
```

**Comment by abhi0001** [comment]
File "/edash_packager/src/packager/media/test/data/bear-640x360.mp4":
Found 2 stream(s).
Stream [0] type: Video
 codec_string: avc1.64001e
 time_scale: 30000
 duration: 82082 (2.7 seconds)
 is_encrypted: false
 codec: H264
 width: 640
 height: 360
 pixel aspect ratio: 1:1
 trick_play_rate: 0
 nalu_length_size: 4

Stream [1] type: Audio
 codec_string: mp4a.40.2
 time_scale: 44100
 duration: 121856 (2.8 seconds)
 is_encrypted: false
 codec: AAC
 sample_bits: 16
 num_channels: 2
 sampling_frequency: 44100
 language: und

Packaging completed successfully.
...this is what i got after executing above commands
i need to know whether my mp4 file should be inside the test/data folder for packing properly

**Comment by abhi0001** [comment]
i tried copying my mp4 file inside test/data and tried executing the mp4 file but it now shows the following error

root@b966d054799c:/media# packager input=/edash_packager/src/packager/media/test/data/example.mp4 --dump_stream_info
[1209/043249:INFO:demuxer.cc(55)] Initialize Demuxer for file '/edash_packager/src/packager/media/test/data/example.mp4'.
[1209/043249:ERROR:packager_main.cc(250)] Demuxer failed to initialize: 5 (FILE_FAILURE): Cannot open file for reading /edash_packager/src/packager/media/test/data/example.mp4

**Comment by kqyang** [comment]
No, you can put it anywhere.

What happens with the first command? 

Can you dump the contents of the file, e.g. using xxd:

```
xxd /media/example.mp4
```

**Comment by kqyang** [comment]
Limit number of bytes:
```
xxd -l 500 /media/example.mp4
```

**Comment by abhi0001** [comment]
this is what i got after executing first command

root@b966d054799c:/media# packager input=/media/example.mp4 --dump_stream_info
[1209/043840:INFO:demuxer.cc(55)] Initialize Demuxer for file '/media/example.mp4'.
[1209/043840:ERROR:demuxer.cc(91)] Not implemented reached in edash_packager::media::Status edash_packager::media::Demuxer::Initialize()
[1209/043840:ERROR:packager_main.cc(250)] Demuxer failed to initialize: 4 (UNIMPLEMENTED): Container not supported.

**Comment by kqyang** [comment]
Can you paste the result of running xxd?

**Comment by abhi0001** [comment]
yeah sure...this is it

root@b966d054799c:/media# xxd -l 500 /media/example.mp4
0000000: 0000 0018 6674 7970 6d70 3432 0000 0000  ....ftypmp42....
0000010: 6d70 3432 6d70 3431 0000 7190 6d6f 6f76  mp42mp41..q.moov
0000020: 0000 006c 6d76 6864 0000 0000 d268 b14f  ...lmvhd.....h.O
0000030: d268 b14f 0001 5f90 0051 db00 0001 0000  .h.O.._..Q......
0000040: 0100 0000 0000 0000 0000 0000 0001 0000  ................
0000050: 0000 0000 0000 0000 0000 0000 0001 0000  ................
0000060: 0000 0000 0000 0000 0000 0000 4000 0000  ............@...
0000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000080: 0000 0000 0000 0000 0000 0003 0000 3add  ..............:.
0000090: 7472 616b 0000 005c 746b 6864 0000 0001  trak...\tkhd....
00000a0: d268 b14f d268 b14f 0000 0001 0000 0000  .h.O.h.O........
00000b0: 0051 cae3 0000 0000 0000 0000 0000 0000  .Q..............
00000c0: 0000 0000 0001 0000 0000 0000 0000 0000  ................
00000d0: 0000 0000 0001 0000 0000 0000 0000 0000  ................
00000e0: 0000 0000 4000 0000 03ae 0000 023a 0000  ....@........:..
00000f0: 0000 0024 6564 7473 0000 001c 656c 7374  ...$edts....elst
0000100: 0000 0000 0000 0001 0051 cae3 0000 03e9  .........Q......
0000110: 0001 0000 0000 3a55 6d64 6961 0000 0020  ......:Umdia... 
0000120: 6d64 6864 0000 0000 d268 b14f d268 b14f  mdhd.....h.O.h.O
0000130: 0000 5dc0 0015 cfb4 15c7 0000 0000 0040  ..]............@
0000140: 6864 6c72 0000 0000 0000 0000 7669 6465  hdlr........vide
0000150: 0000 0000 0000 0000 0000 0000 1f4d 6169  .............Mai
0000160: 6e63 6f6e 6365 7074 2056 6964 656f 204d  nconcept Video M
0000170: 6564 6961 2048 616e 646c 6572 0000 39ed  edia Handler..9.
0000180: 6d69 6e66 0000 0014 766d 6864 0000 0001  minf....vmhd....
0000190: 0000 0000 0000 0000 0000 0033 6864 6c72  ...........3hdlr
00001a0: 0000 0000 0000 0000 616c 6973 0000 0000  ........alis....
00001b0: 0000 0000 0000 0000 416c 6961 7320 4461  ........Alias Da
00001c0: 7461 2048 616e 646c 6572 0000 0000 2464  ta Handler....$d
00001d0: 696e 6600 0000 1c64 7265 6600 0000 0000  inf....dref.....
00001e0: 0000 0100 0000 0c75 726c 2000 0000 0100  .......url .....
00001f0: 0039 7a73                                .9zs

**Comment by abhi0001** [comment]
it is same for all mp4 files ....container not supported

**Comment by kqyang** [comment]
Don't know yet why, what packager sees is different to what xxd sees.

Can you edit /edash_packager/src/packager/media/base/demuxer.cc and add the below lines before line 74: container_name_ = DetermineContainer(...)

```C++
  LOG(INFO) << "Read bytes " << bytes_read;
  for (size_t i = 0; i < std::min(bytes_read, 256ul); ++i) {
    if ((i % 16) == 0) fprintf(stdout, "\n");
    fprintf(stdout, "%02x ", buffer_.get()[i]);
  }
```

Then compile edash-packager and run example.mp4 again:

```bash
cd /edash_packager/src
ninja -C out/Release
packager input=/media/example.mp4 --dump_stream_info
```

**Comment by abhi0001** [comment]
now i am trying to run ninja it is not working showing error
OptiPlex-3020:~/edash_packager/src$ ninja
log: warning: no configuration file specified, using default values
log: ninja version 0.1.3 initializing
die: error: must run as root

**Comment by abhi0001** [comment]
previously it was working like charm....y is that

**Comment by abhi0001** [comment]
and 
cd /edash_packager/src
ninja -C out/Release
packager input=/media/example.mp4 --dump_stream_info
should i execute inside container??

**Comment by kqyang** [comment]
Yes, it should be executed inside the container.

**Comment by abhi0001** [comment]
thank you very very much for spending your valuable time its working fine ...if i get any more issues while working will ping you hope you dont mind...

**Comment by abhi0001** [comment]
i am getting another error while encrypting the file 

root@d109c0040b23:/media# packager input=media/example.mp4,stream=video,output=demo/encrypted_sintel.mp4 \
> --enable_widevine_encryption \
> --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
> --content_id "3031323334353637" \
> --signer "widevine_test" \
> --rsa_signing_key_path "widevine_test_private.der"
[1209/062541:ERROR:packager_util.cc(54)] Failed to read from 'widevine_test_private.der'.

**Comment by kqyang** [comment]
So what is the problem earlier? Something wrong with the file path?

**Comment by abhi0001** [comment]
i edited the code what you gave for demuxer.cc and it worked fine all steps except the encryption....i got stuck there and wanted to know if i can use that cenc widevine encryption for free or not and if not which encryption with edash packager is best and how to use it some guide for that

**Comment by abhi0001** [comment]
i need no services like widevine or any paid service just want to have
video encryption with edash packager i will be providing with the key to
encrypt or might it b generated ........thats why i was looking for the
clear key encryption but i did'nt find any details of encryption other than
using widevine .......will you please tell me how to do the video
encryption without any paid service with edash with the steps cause i saw
edash uses PSSh boxes but no guidelines are on google .............i will
be really gtrful to you if you kindly provide me with such technique for
encryption with the steps how to use with the edash packager
