### ISSUE TITLE
 Failed to read from 'widevine_test_private.der'

### ISSUE THREAD

**Issue by abhi0001** [google/edash-packager#54]
it is not able to read from the url mentioned
root@d109c0040b23:/media# packager input=media/example.mp4,stream=video,output=demo/encrypted_sintel.mp4 \
> --enable_widevine_encryption \
> --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
> --content_id "3031323334353637" \
> --signer "widevine_test" \
> --rsa_signing_key_path "widevine_test_private.der"
[1209/062541:ERROR:packager_util.cc(54)] Failed to read from 'widevine_test_private.der'.
..........and even if you go to the url 404 error

**Comment by kqyang** [comment]
You'll need to have the key file "widevine_test_private.der". If you don't have it, use aes key instead:

--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"

**Comment by abhi0001** [comment]
how to use clear key encryption with edash packager??? or pssh box as mentioned steps where can i provide them??

**Comment by abhi0001** [comment]
i need no services like widevine or any paid service just want to have video encryption with edash packager i will be providing with the key to encrypt or might it b generated ........thats why i was looking for the clear key encryption but i did'nt find any details of encryption other than using widevine .......will you please tell me how to do the video encryption without any paid service with edash with the steps cause i saw edash uses PSSh boxes but no guidelines are on google .............i will be really gtrful to you if you kindly provide me with such technique for encryption with the steps how to use with the edash packager

**Comment by abhi0001** [comment]
one more thing i just wanted to ask when i am trying to check my mpd file trying to validate it using http://dashif.org/conformance.html site only xlink i can see is fine mpd and schematron are not validated

**Comment by kqyang** [comment]
Thanks for reporting the issue. I have open #55 to track the bug.

As for clear key support, you can encrypt the content with --enable_fixed_key_encryption (just run packager alone without parameters will print all available options)

```bash
--enable_fixed_key_encryption --key {some key} --key_id {some key id value} -pssh {some pssh value}
```

You may use the same value for pssh and key id.

In the player side, you can listen to the init events and provide the keys according to the init data.

Also, Widevine license service is free. That is another option for you if you don't want to manage the keys yourself.

**Comment by abhi0001** [comment]
heads up encryption is done thanks to you helping me from the beginning
.....i need the commends for the segmentation can you please post the
commands for that as you did that for encryption...

**Comment by abhi0001** [comment]
heads up encryption is done thanks to you helping me from the beginning .....i need the commends for the segmentation can you please post the commands for that as you did that for encryption...

**Comment by kqyang** [comment]
Segmentation/Fragmentation is performed by default. 

For on-demand profile, all segments and fragments are contained in the same file. A DASH player is able to do progress downloading of the segments.

For live profiles, use something like below to split it into multiple files:

```
input=xx,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000
```

See examples at https://github.com/google/edash-packager#driver-program-sample-usage.

**Comment by abhi0001** [comment]
i guess the extention of the segmented videos will be .m4s i did'nt find
files with such extension for the videos i encryptrd as u said it will be
done by default...i want those files how to get those .m4s files..
thank you!!

**Comment by abhi0001** [comment]
and widevive you said it provides free licence which link should i use to
get that can you get me the format ...please

**Comment by kqyang** [comment]
Have you read my message above, i'll just repeat it here:

You'll need to specify what the output file is. Note that it should be used for live profile only. For on-demand profile, it should not be used.
```
input=xx,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.m4s,bandwidth=2000000
```

For Widevine license, go to http://www.widevine.com/contact.html, click "Contact Us" then send a "General / Sales" inquiry. Someone will get back to you and walk through the steps to set it up.

**Comment by abhi0001** [comment]
root@e5ef7453cd43:/media# packager 'input=example_video.mp4,stream=video,init_segment=ex_seg_video.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000' 'input=example_audio.mp4,stream=audio,init_segment=ex_seg_audio.mp4,segment_template=live-audio-$Number$.mp4,bandwidth=130000'  --mpd_output ex_live.mpd --enable_fixed_key_encryption --key "123400000000000000000000000" --key_id "abcd1234" -pssh "abcd1234"
[1215/064519:ERROR:key_source.cc(113)] Cannot parse key_hex 123400000000000000000000000
----------
the above error i am getting if i am trying to encrypt my audio and video files for the mpd
or
if i change the value for the keyi get the following error
--------------
root@e5ef7453cd43:/media# packager 'input=example_video.mp4,stream=video,init_segment=ex_seg_video.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000' 'input=example_audio.mp4,stream=audio,init_segment=ex_seg_audio.mp4,segment_template=live-audio-$Number$.mp4,bandwidth=130000'  --mpd_output ex_live.mpd --enable_fixed_key_encryption --key "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" --key_id "abcd1234" -pssh "abcd1234"
[1215/064957:INFO:demuxer.cc(55)] Initialize Demuxer for file 'example_audio.mp4'.
[1215/064957:INFO:demuxer.cc(55)] Initialize Demuxer for file 'example_video.mp4'.
[1215/064957:INFO:demuxer.cc(139)] Demuxer::Run() on file 'example_audio.mp4'.
[1215/064957:INFO:demuxer.cc(139)] Demuxer::Run() on file 'example_video.mp4'.
[1215/064957:ERROR:aes_encryptor.cc(67)] Invalid key size of 15 for CENC.
[1215/064957:ERROR:mp4_media_parser.cc(600)] Failed to process the sample.
[1215/064957:ERROR:aes_encryptor.cc(67)] Invalid key size of 15 for CENC.
[1215/064957:ERROR:mp4_media_parser.cc(600)] Failed to process the sample.
[1215/064957:ERROR:packager_main.cc(401)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file example_audio.mp4
-----------
need a bit help in this just give me an example for providing the key value
thank you

**Comment by abhi0001** [comment]
i fixed that it showed
-----------------------
root@e5ef7453cd43:/media# packager 'input=example_video.mp4,stream=video,init_segment=ex_seg_video.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000' 'input=example_audio.mp4,stream=audio,init_segment=ex_seg_audio.mp4,segment_template=live-audio-$Number$.mp4,bandwidth=130000'  --mpd_output ex_live.mpd --enable_fixed_key_encryption --key 'd58ce954203b7c9a9a9d467f59839249' --key_id "abcd1234abcd1234abcd1234abcd1234" -pssh "abcd1234"
[1215/070855:INFO:demuxer.cc(55)] Initialize Demuxer for file 'example_audio.mp4'.
[1215/070855:INFO:demuxer.cc(55)] Initialize Demuxer for file 'example_video.mp4'.
[1215/070855:INFO:demuxer.cc(139)] Demuxer::Run() on file 'example_audio.mp4'.
[1215/070855:INFO:demuxer.cc(139)] Demuxer::Run() on file 'example_video.mp4'.
[1215/070855:INFO:single_segment_segmenter.cc(117)] Update media header (moov) and rewrite the file to 'ex_seg_audio.mp4'.
[1215/070855:INFO:single_segment_segmenter.cc(117)] Update media header (moov) and rewrite the file to 'ex_seg_video.mp4'.
[1215/070855:INFO:mp4_muxer.cc(151)] MP4 file 'ex_seg_audio.mp4' finalized.
[1215/070855:INFO:mp4_muxer.cc(151)] MP4 file 'ex_seg_video.mp4' finalized.
Packaging completed successfully.
--------------
but if i am trying to play the mpd file with dash its not playing playing time is shown but not playing 
...........this is all i want it to play the encrypted mpd

**Comment by imalex** [comment]
I think you should start here instead of using the edash packager right off the bat:

http://www.html5rocks.com/en/tutorials/eme/basics/

**Comment by abhi0001** [comment]
i have already been to that link .....everything is done on edash except that after encryption that mpd file is not playing a little help on that will be useful....

**Comment by abhi0001** [comment]
this is the mpd file i am trying to play before encryption it is working but after its not

[mpdfile.txt](https://github.com/google/edash-packager/files/62249/mpdfile.txt)

**Comment by kqyang** [comment]
Have you tried EME link provided by Alex: http://www.html5rocks.com/en/tutorials/eme/basics/?

You need to update your player client to provide appropriate license.

**Comment by abhi0001** [comment]
i didnt find anything for updating my player in the link alex provided with.....
i am sending u the js and html files which i am using as a player 
[dashalljs.txt](https://github.com/google/edash-packager/files/63527/dashalljs.txt)
[index.txt](https://github.com/google/edash-packager/files/63528/index.txt)

the dash.all.js was the file i made it as .txt so i can attach for sending it to u ....so how you want me to update player client...thank you

**Comment by kqyang** [comment]
Here is the sample code I copied from eme link above: 

(You'll need to update this code to the right content type and key)

```
// Define a key: hardcoded in this example
// – this corresponds to the key used for encryption
var KEY = new Uint8Array([
  0xeb, 0xdd, 0x62, 0xf1, 0x68, 0x14, 0xd2, 0x7b,
  0x68, 0xef, 0x12, 0x2a, 0xfc, 0xe4, 0xae, 0x3c
]);

var config = [{
  initDataTypes: ['webm'],
  videoCapabilities: [{
    contentType: 'video/webm; codecs="vp8"'
  }]
}];

var video = document.querySelector('video');
video.addEventListener('encrypted', handleEncrypted, false);

navigator.requestMediaKeySystemAccess('org.w3.clearkey', config).then(
  function(keySystemAccess) {
    return keySystemAccess.createMediaKeys();
  }
).then(
  function(createdMediaKeys) {
    return video.setMediaKeys(createdMediaKeys);
  }
).catch(
  function(error) {
    console.error('Failed to set up MediaKeys', error);
  }
);

function handleEncrypted(event) {
  var session = video.mediaKeys.createSession();
  session.addEventListener('message', handleMessage, false);
  session.generateRequest(event.initDataType, event.initData).catch(
    function(error) {
      console.error('Failed to generate a license request', error);
    }
  );
}

function handleMessage(event) {
  // If you had a license server, you would make an asynchronous XMLHttpRequest
  // with event.message as the body.  The response from the server, as a
  // Uint8Array, would then be passed to session.update().
  // Instead, we will generate the license synchronously on the client, using
  // the hard-coded KEY at the top.
  var license = generateLicense(event.message);

  var session = event.target;
  session.update(license).catch(
    function(error) {
      console.error('Failed to update the session', error);
    }
  );
}

// Convert Uint8Array into base64 using base64url alphabet, without padding.
function toBase64(u8arr) {
  return btoa(String.fromCharCode.apply(null, u8arr)).
      replace(/\+/g, '-').replace(/\//g, '_').replace(/=*$/, '');
}

// This takes the place of a license server.
// kids is an array of base64-encoded key IDs
// keys is an array of base64-encoded keys
function generateLicense(message) {
  // Parse the clearkey license request.
  var request = JSON.parse(new TextDecoder().decode(message));
  // We only know one key, so there should only be one key ID.
  // A real license server could easily serve multiple keys.
  console.assert(request.kids.length === 1);

  var keyObj = {
    kty: 'oct',
    alg: 'A128KW',
    kid: request.kids[0],
    k: toBase64(KEY)
  };
  return new TextEncoder().encode(JSON.stringify({
    keys: [keyObj]
  }));
}
```

**Comment by abhi0001** [comment]
i understand that my question is getting quiet irritating for you but i
want to know which file you want me to modify ...i mean which file i would
find the above content for modifying it ....and i see the encrypted video
from the http://www.html5rocks.com/en/tutorials/eme/basics/ site works
totally fine but it is not working for me

**Comment by abhi0001** [comment]
plz i need help in playing that encrypted file with dash

**Comment by kqyang** [comment]
@abhi0001 Here is a tutorial on Shaka-player. It is probably easier for you to start with: https://shaka-player-demo.appspot.com/docs/index.html

I am closing this bug. Feel free to reopen it if you have more questions.
