### ISSUE TITLE
AES-128

### ISSUE THREAD

**Issue by brylek** [google/edash-packager#57]
All,

I do have question, as far as I know dash packager supports DRM and AES encryption, My question is can I use only AES encryption without DRM? if yes, any example? :) and what is your experience with AES&MPEG-DASH on windows mobile and web browsers as chrome/firefox/opera?

thx,
Lukasz

**Comment by kqyang** [comment]
I assume you are talking about clear key support. It is not fully supported yet (you can encrypt the content by providing the keys, but we still generate Widevine pssh - we are planning to have full clear key support soon).

As for the support on various browsers, @joeyparrish do you know whether firefox and opera support EME?

Thanks.

**Comment by joeyparrish** [comment]
@brylek, clearkey is not secure, as the keys have to be provided in the clear.  But here's the status of EME support in the major browsers:

Chrome 31+ (last 2 years) supports MSE & EME.  Chrome ships with clearkey CDM and Widevine CDM is downloaded at runtime.

Opera 18+ (last 2 years) supports MSE & EME.  As of Opera 33 (latest stable), it still seems to only have the clearkey CDM.

IE11+ on Windows 8.1+ supports MSE & EME, but only has a PlayReady CDM, no clearkey.

Safari 8+ on OSX 10.10.5+ supports MSE & EME, but only has a FairPlay CDM, no clearkey.

Firefox 42 (latest stable) does not support EME yet.

**Comment by kqyang** [comment]
Thanks @joeyparrish!

@brylek I'll close this issue. Feel free to re-open it if you have more questions.

**Comment by brylek** [comment]
hi Guys, sorry, I couldn't answer yesterday. 
@kqyang - Yes, I am talking about pure AES encryption. 
@joeyparrish - thx, very helpful feedback

**Comment by brylek** [comment]
Guys,

I assume you are very close to widevine project as well :) If not - sorry for bothering you :) I've checked "Supported Platforms" on widevine web page, I can not find Windows Molbile there. I have a plan to create OTT platform with encryption but Windows Mobile looks like a bottleneck here...

**Comment by imalex** [comment]
Windows Phone is not currently supported at this time (does not have a
Widevine CDM)

**Comment by brylek** [comment]
thx, very helpful
