### ISSUE TITLE
Does VOD profile support "SegmentTimeline" MPD generation?

### ISSUE THREAD

**Issue by hexiay** [google/edash-packager#62]

**Comment by Sean-X** [comment]
it doesn't support

**Comment by kqyang** [comment]
I am assuming you are referring to generate MPD with multiple segments specified using either SegmentList or SegmentTemplate. It is against DASH spec, see ISO/IEC 23009-1 8.3 ISO Base media file format On Demand profile for details. 

```
- neither the Period.SegmentList element nor the Period.SegmentTemplate element shall be present 
- for Adaptation Sets conforming to this profile 
  - if either the AdaptationSet.SegmentList or the AdaptationSet.SegmentTemplate element is present in an AdaptationSet element then this AdaptationSet element may be ignored. 
  - if either the Representation.SegmentList or the Representation.SegmentTemplate element is present in a Representation element then this Representation element may be ignored. 
```

That said, if there is a strong request for this feature, we can consider supporting it in a future revision. We will probably use "“urn:mpeg:dash:profile:isoff-main:2011” profile to be compliant to DASH spec.
