### ISSUE TITLE
SPS with "gaps_in_frame_num_value_allowed_flag=1"

### ISSUE THREAD

**Issue by FeiCao** [google/edash-packager#63]
Hi, I have a video source that SPS with "gaps_in_frame_num_value_allowed_flag=1", and I know the packager do not surport now, but I want to modify the code to parse this video, can you give me some advices about how and where I need to modify, thank you

**Comment by kqyang** [comment]
+ @tinskip 

Hi Fei,

It might be sufficient to just remove the two lines at https://github.com/google/edash-packager/blob/8fc7f51d81d62054f035240048f786886c9993e1/packager/media/filters/h264_parser.cc#L850

Let us know how it goes :)

**Comment by FeiCao** [comment]
Thank you, packager can make video segments, but there is something wrong with mpd file, the player can not play normally.
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="dynamic" profiles="urn:mpeg:dash:profile:isoff-live:2011" availabilityStartTime="2016-01-08T06:30:13Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period start="PT0S">
    <AdaptationSet id="0" contentType="video" width="640" height="480" frameRate="90000/6000" segmentAlignment="true" par="4:3">
      <Representation id="0" bandwidth="2000000" codecs="avc1.4d001e" mimeType="video/mp4" sar="1:1" width="640" height="480" frameRate="90000/6000">
        <SegmentTemplate timescale="90000" initialization="7079802007652959010//live-video-sd.mp4" media="7079802007652959010//live-video-sd-$Number$.mp4" startNumber="1">
          <SegmentTimeline>
            <S t="6000" d="216000"/>
            <S t="222000" d="204000"/>
            <S t="426000" d="264000"/>
            <S t="690000" d="204000"/>
            <S t="894000" d="270000"/>
            <S t="1164000" d="204000"/>
            <S t="1368000" d="270000"/>
            <S t="1638000" d="204000"/>
            <S t="1842000" d="264000"/>
            <S t="2106000" d="204000"/>
            <S t="2310000" d="264000"/>
            <S t="2574000" d="204000"/>
            <S t="2778000" d="264000"/>
            <S t="3042000" d="204000"/>
            <S t="3246000" d="264000"/>
            <S t="3510000" d="204000"/>
            <S t="3714000" d="264000"/>
            <S t="3978000" d="204000"/>
            <S t="4182000" d="270000"/>
            <S t="4452000" d="204000"/>
            <S t="4656000" d="264000"/>
            <S t="4920000" d="204000"/>
            <S t="5124000" d="270000"/>
            <S t="5394000" d="204000"/>
            <S t="5598000" d="264000"/>
            <S t="5862000" d="204000"/>
            <S t="6066000" d="264000"/>
            <S t="6330000" d="204000"/>
            <S t="6534000" d="258000"/>
            <S t="6792000" d="204000"/>
            <S t="6996000" d="264000"/>
            <S t="7260000" d="204000"/>
            <S t="7464000" d="270000"/>
            <S t="7734000" d="204000"/>
            <S t="7938000" d="264000"/>
            <S t="8202000" d="204000"/>
            <S t="8406000" d="264000"/>
            <S t="8670000" d="204000"/>
            <S t="8874000" d="264000"/>
            <S t="9138000" d="204000"/>
            <S t="9342000" d="264000"/>
            <S t="9606000" d="204000"/>
            <S t="9810000" d="264000"/>
            <S t="10074000" d="204000"/>
            <S t="10278000" d="270000"/>
            <S t="10548000" d="204000"/>
            <S t="10752000" d="264000"/>
            <S t="11016000" d="204000"/>
            <S t="11220000" d="264000"/>
            <S t="11484000" d="204000"/>
            <S t="11688000" d="264000"/>
            <S t="11952000" d="204000"/>
            <S t="12156000" d="180000"/>
            <S t="12336000" d="216000"/>
            <S t="12552000" d="180000"/>
            <S t="12732000" d="204000"/>
            <S t="12936000" d="264000"/>
            <S t="13200000" d="204000"/>
            <S t="13404000" d="264000"/>
            <S t="13668000" d="204000"/>
            <S t="13872000" d="264000"/>
            <S t="14136000" d="204000"/>
            <S t="14340000" d="264000"/>
            <S t="14604000" d="204000"/>
            <S t="14808000" d="270000"/>
            <S t="15078000" d="204000"/>
            <S t="15282000" d="264000"/>
            <S t="15546000" d="204000"/>
            <S t="15750000" d="264000"/>
            <S t="16014000" d="204000"/>
            <S t="16218000" d="264000"/>
            <S t="16482000" d="204000"/>
            <S t="16686000" d="264000"/>
            <S t="16950000" d="204000"/>
            <S t="17154000" d="258000"/>
            <S t="17412000" d="204000"/>
            <S t="17616000" d="264000"/>
            <S t="17880000" d="204000"/>
            <S t="18084000" d="264000"/>
            <S t="18348000" d="204000"/>
            <S t="18552000" d="264000"/>
            <S t="18816000" d="204000"/>
            <S t="19020000" d="270000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

**Comment by kqyang** [comment]
Can you upload a mpd (maybe with video segments as well) somewhere so we can take a look?

**Comment by kqyang** [comment]
This issue has been inactive for some time. I'll close for now. Feel free to re-open it if needed.
