### ISSUE TITLE
Support building with Ninja on MacOSX

### ISSUE THREAD

**Issue by nevil** [google/edash-packager#65]
It would be convenient to have support for building on MacOSX.
Xcode support is not necessary. Supporting Ninja is enough.

**Comment by nevil** [comment]
Being worked on in https://github.com/google/edash-packager/pull/66

**Comment by kqyang** [comment]
Hey nevil, thanks for supporting edash-packager and improving this project! The changes look good to me, with just a couple of nits.

**Comment by kqyang** [comment]
I have merged the pull request.
@nevil thanks for your work on MacOSX and thanks for the contribution to edash-packager project!
