### ISSUE TITLE
Building on ubuntu server

### ISSUE THREAD

**Issue by sinkers** [google/edash-packager#7]
I was trying to build on ubuntu 64bit server and getting the error below. 

What I found was the version of gold included with depot tools was older than the system version and the depot tools version didn't have the -plugin option. So I linked the system version to the depot tools path and it compiled.

FAILED: c++ -Wl,-z,now -Wl,-z,relro -pthread -Wl,-z,noexecstack -fPIC -B/home/sinclair/edash_packager/src/packager/third_party/gold -Wl,--icf=none -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o protoc -Wl,--start-group obj/third_party/protobuf/src/google/protobuf/compiler/protoc.code_generator.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.command_line_interface.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.plugin.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.plugin.pb.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.subprocess.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.zip_writer.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_enum.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_enum_field.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_extension.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_field.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_file.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_generator.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_helpers.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_message.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_message_field.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_primitive_field.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_service.o obj/third_party/protobuf/src/google/protobuf/compiler/cpp/protoc.cpp_string_field.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_enum.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_enum_field.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_extension.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_field.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_file.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_generator.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_helpers.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_message.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_message_field.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_primitive_field.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_service.o obj/third_party/protobuf/src/google/protobuf/compiler/java/protoc.java_string_field.o obj/third_party/protobuf/src/google/protobuf/compiler/python/protoc.python_generator.o obj/third_party/protobuf/src/google/protobuf/compiler/protoc.main.o obj/third_party/protobuf/libprotobuf_full_do_not_use.a  -Wl,--end-group
/home/sinclair/edash_packager/src/packager/third_party/gold/gold64: -plugin: unknown option
/home/sinclair/edash_packager/src/packager/third_party/gold/gold64: use the --help option for usage information
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by kqyang** [comment]
Thanks for reporting the issue. We will look into it and address the problem soon.

**Comment by kqyang** [comment]
I did some testing with and without gold. There are some speed gains with gold, but the improvement is not significant on most of the platforms we tested. I will create a CL to disable gold by default. The users can still enable gold if they want with: 

GYP_DEFINES="linux_use_gold_binary=1 linux_use_gold_flags=1" gclient runhooks
