### ISSUE TITLE
change the resolution of a stream, how to change the packager 

### ISSUE THREAD

**Issue by FeiCao** [google/edash-packager#73]
Hi, I start the steam with 1280x800 and change the resolution to 320x200 later. player play abnormally, something like mosaic. Does the packager not support that change the resolution? If not, how to do?
 thank you!

**Comment by kqyang** [comment]
Hi Fei Cao, 

DASH does not support changing resolutions in a single stream - there is no point of doing that as well. 

https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP

You can create multiple streams with different resolutions and packaged into a single manifest. A DASH player can select a stream based on network conditions, device capabilities and user preferences, enabling adaptive bitrate streaming and QoE (Quality of Experience) fairness.
