### ISSUE TITLE
Add support for pattern encryption cbcs and cens

### ISSUE THREAD

**Issue by kqyang** [google/edash-packager#78]
Added in CENC spec v3.

> Pattern encryption utilizes a pattern of encrypted and clear (“skipped”) 16 byte Blocks over the protected range of a Subsample. 

> When the fields default_crypt_byte_block and default_skip_byte_block in a version 1 Track Encryption Box (‘tenc’) are non-zero numbers, pattern encryption SHALL be applied. 

> The pattern SHALL consist of the number of encrypted cipher blocks indicated by the field default_crypt_byte_block or crypt_byte_block (if present in a sample group description) followed by the number of unencrypted sample data Blocks indicated by the field default_skip_byte_block or skip_byte_block (if present in a sample group description).

> If the last Block pattern in a Subsample is incomplete, the partial pattern SHALL be followed until truncated by the BytesOfProtectedData size, and any partial crypt_byte_block SHALL remain unencrypted. 

> The ‘cens’ scheme SHALL apply an IV to the first encrypted cipher block of each sample (same as ‘cenc’ and ‘cbc1’ schemes without pattern encryption).

> The ‘cbcs’ scheme SHALL apply an IV to the first encrypted cipher block of each Subsample.

**Comment by xieunext** [comment]
Hi
It seems like exoplayer couldn't playback contents encrypted by cbcs scheme on android OS 6.x devices.
Does it mean it's not supported by android cdm or do I need to upgrade it to android OS 7.x?

**Comment by kqyang** [comment]
I don't think exoplayer supports cbcs scheme right now. Some updates needs to happen there.

**Comment by xieunext** [comment]
So you mean the android widewine supports cbcs scheme. If we add some update to exoplayer, we could play contents on android device with contents encrypted by cbcs scheme?

**Comment by ojw28** [comment]
- ExoPlayer does need some (fairly minor) changes to support the cens, cbc1 and cbcs schemes.
- Widevine added support cens, cbc1, and cbcs in API level 24. So even once ExoPlayer does support the additional schemes, it will only be possible to use them when running on a device running API level 24 (i.e. Nougat) or later.
