### ISSUE TITLE
AES signing error....

### ISSUE THREAD

**Issue by nibaboojit** [google/edash-packager#8]
hi
I'm used edash_packager for widevine modular drm AES encrypt test.
I used resource 
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \

but, today suddenly this error message occurred.

[0227/193438:ERROR:http_key_fetcher.cc(108)] curl_easy_perform() failed: Couldn't resolve host name.
[0227/193438:ERROR:packager_util.cc(87)] Widevine encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: Couldn't resolve host name.

what's wrong?

**Comment by kqyang** [comment]
It sounds like there is a network problem. Can you make sure there is network connection when issuing the request? You may try "curl https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" to see what is coming back. It should fail with error 400.

**Comment by nibaboojit** [comment]
my ubuntu server has network error.. 
and solve this problem.
thx!  :)
