### ISSUE TITLE
MacOSX build doesn't use c++11 enabled stdlib

### ISSUE THREAD

**Issue by nevil** [google/edash-packager#80]
The MacOSX build is currently using the old GNU libstdc++. This library does not support C++11.
This is currently causing build errors in ec3_audio_util_unittest.cc.
```
   ../../packager/media/filters/ec3_audio_util_unittest.cc:17:30: error: no matching constructor for initialization of 'const std::vector<uint8_t>'
  const std::vector<uint8_t> ec3_data = {0, 0, 0, 0x0f, 0};
                             ^          ~~~~~~~~~~~~~~~~~~

../../packager/media/filters/ec3_audio_util_unittest.cc:26:30: error: no matching constructor for initialization of 'const std::vector<uint8_t>'
  const std::vector<uint8_t> ec3_data = {0, 0, 0, 0x04, 0};
                             ^          ~~~~~~~~~~~~~~~~~~

../../packager/media/filters/ec3_audio_util_unittest.cc:36:30: error: no matching constructor for initialization of 'const std::vector<uint8_t>'
  const std::vector<uint8_t> ec3_data = {0, 0, 0, 0x07, 0x07, 0x03};
                             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

A solution is proposed in https://github.com/google/edash-packager/pull/79.

**Comment by kqyang** [comment]
@nevil Thanks for reporting this issue. We follow Chromium C++11 usage guide: http://chromium-cpp.appspot.com. This code shouldn't be checked in in the first place. We will fix the usage here, so it compiles with stdlibc++.

**Comment by kqyang** [comment]
We don't have automatic testing for MAC OS currently. We will consider setting up automatic testing for MAC so this kinds of issue can be detected early.
