### ISSUE TITLE
Temporary files in /tmp are not deleted after execution

### ISSUE THREAD

**Issue by Badaro** [google/edash-packager#9]
Files named ".org.chromium.Chromium.XXXXXX" (where X is a random letter) are being left in the /tmp folder after each packaging process.

These files appear to be roughly the same size as the videos encrypted, and accumulate over time eventually causing the disk to fill. This forces the setup of a separate cleanup process for this folder, as well as the usage of a larger than necessary /tmp partition.

It would be optimal if edash-packager removed these files after the process is completed.

**Comment by kqyang** [comment]
Sounds good. We'll fix it.

**Comment by kqyang** [comment]
Sounds good. We'll fix it.

**Comment by tinskip** [comment]
Fixed.
