### ISSUE TITLE
[WebM] Packaging failed on a test content: Cluster::AddFrame failed

### ISSUE THREAD

**Issue by kqyang** [google/edash-packager#90]
Content: https://storage.googleapis.com/blockbuster/temp_clear/vp9_test_VP9_320_2M.WEBM

Command to duplicate: ./packager input=vp9_test_VP9_320_2M.WEBM,stream=video,output=out.webm

Need to investigate to see if it is content problem or packager bug.

**Comment by TheModMaker** [comment]
The content only has one key-frame, which is a transcoder problem.  The default is to only split Clusters on key-frames, so it creates one large Cluster.  This causes a problem since the frame's relative timestamp needs to be stored as a 16-bit integer.  If you pass ```--segment_sap_aligned=false``` it will work properly.
