### ISSUE TITLE
Widevine encrypted content fails in Chrome

### ISSUE THREAD

**Issue by peyoh** [google/edash-packager#95]
Hello,
I've opened issue in shaka player 
[The link to shaka issue ticket](https://github.com/google/shaka-player/issues/309)
It's a live stream encrypted with Widevine, but I'm unable to decode it on Chrome. 
Please take a look at this issue. I'm not sure if this is edash-packager issue, but I'm completely sure that August 2015 there was no such problem.Of course Chrome and edash was different version. Unfortunately I can't remember versions:(.
I will check later with a previous version on the packager.

If you need additional information just tell me.
I can provide ssh access, widevine test key, example streams, etc. 

BRS

**Comment by kqyang** [comment]
This is a known problem introduced in 96abd90ca29bda736e0ddb3ec1bd34aab977c559. It has been fixed in 1863f5a569340132760ac3081c70a249ed72ff14. Please try with the latest code @ master. Sorry about the inconvenience.

**Comment by peyoh** [comment]
Hi,
I'm closing this to keep the environment clean until the test.

**Comment by peyoh** [comment]
Uff, sorry.

**Comment by kqyang** [comment]
I guess you probably picked up the unstable version of edash-packager when debugging https://github.com/google/edash-packager/issues/93... 

We'll have a solution for https://github.com/google/edash-packager/issues/93 soon.

**Comment by peyoh** [comment]
Yes, that's true.

**Comment by peyoh** [comment]
Hi kqyang, 
with master it is ok for SD channels now. 
But what can be the reason to fails again on HD?
