### ISSUE TITLE
C++ SDK installation

### ISSUE THREAD

**Issue by Tomtom777** [google/edash-packager#98]
Hello,

Is there a simple way to install the C++ edash-packager libraries (ubuntu) ?

I need to use edash-packager as a C++ SDK. 

When I tried to build **Packager** and **MPD_Generator**  examples by myself, I had some "_no such file or  directory_" errors with the header files (I tried it several times keeping the original files organization and other times moving the files tree into the _/usr/include_  directory). 

Thank you

**Comment by kqyang** [comment]
I'd like to understand more about your use case and your development environment. 

Also, have you managed to build Packager successfully? If you follow instructions at the [readme](https://github.com/google/edash-packager) page, it should be straight-forward.

**Comment by Tomtom777** [comment]
Yes, I succeed to compile and run Packager following the readme page but if I include the libraries in a new c++ program, the compiler fail to find them...

I'm using g++ and a standard c++ text editor on a Ubuntu server Virtual Machine.
thanks

**Comment by kqyang** [comment]
@Tomtom777  Have you managed to get the library to work? I am preparing a document (step by step guide) on this if you haven't figured it out.
