### ISSUE TITLE
Invalid SegmentBase Index Ranges

### ISSUE THREAD

**Issue by chartelt** [google/edash-packager#99]
With version 
`<!--Generated with https://github.com/google/edash-packager version e39c357-debu                                   g-->`

generated Manifests show ranges which prohibit playback (webm case).

For example an entry looks like:
`<BaseURL>1.webm</BaseURL>
        <SegmentBase indexRange="14198634-14199331" timescale="1000000">
          <Initialization range="0-333"/>
        </SegmentBase>`

And invalid ranges are used by resulting HTTP requests.
Changing the above to:

`<BaseURL>1.webm</BaseURL>
        <SegmentBase indexRange="14198634-14199330" timescale="1000000">
          <Initialization range="0-333"/>
        </SegmentBase>`

And playback works on Exoplayer. Dash.js fails, possibly since the SIDX box still contains an invalid range.

**Comment by kqyang** [comment]
Thanks for reporting the issue. Looks like the end offset is off-by-1. We'll look into the problem right away. Stay tuned!

**Comment by kqyang** [comment]
@chartelt The playback problem on Exoplayer should be fixed. As for Dash.js, it is expected to fail as initialization data format is different in WebM, see this link for details: http://wiki.webmproject.org/adaptive-streaming/webm-dash-specification. Some updates in Dash.js is needed. You may consider using [shaka-player](https://github.com/google/shaka-player) instead.

Let us know if there is any other problems. Again, thanks for reporting the problem!

**Comment by chartelt** [comment]
Thank you for all the additional info and the quick reaction!
